# csmeg tester build file for Scons
sourcedir = "src"
includedir = "include"
shaderdir = "shaders"
texturedir = "textures"

export_shaders = Glob(shaderdir + '/*.*')
export_textures = Glob(texturedir + '/*.*')
project_sources = Glob(sourcedir + '/*.cpp')

Import('env', 'project', 'mymode', 'debug_flags', 'release_flags')
localenv = env.Clone()

buildroot = '../' + mymode
builddir = buildroot + '/' + project
targetpath = builddir + '/' + project

if mymode == 'debug':
	localenv.Append(CPPFLAGS=debug_flags)
else:
	localenv.Append(CPPFLAGS=release_flags)

localenv.Append(CPPPATH=['include', buildroot + '/csmegfw/include'])
tlib = File(buildroot + '/csmegfw/libcsmegfw.a');
localenv.Append(LIBS=[tlib, 'SDL2', 'GL', 'GLEW', 'boost_system', 'boost_filesystem', 'SOIL'])

localenv.VariantDir(builddir, ".", duplicate=0)

localenv.Program(target = targetpath, source = project_sources)

localenv.Install(builddir, shaderdir)
localenv.Install(builddir, texturedir)
